remote_theme: eliottvincent/bay

title: Sofia Andrade
description: >- # this means to ignore newlines until "baseurl:"
   Bay is a minimal Jekyll Theme.
baseurl: "/bay" # the subpath of the site
url: "https://sofiandrade.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: sofi.andrade10@gmail.com
      link: mailto:sofi.andrade10gmail.com
  follow:
    - name: Twitter
      link: http://twitter.com/SofiaAndrade__
      username: "@SofiaAndrade__"
    - name: LinkedIn
      link: http://linkedin.com/in/sofia-andrade1


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
