remote_theme: eliottvincent/bay

title: Bay Jekyll Theme
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/bay" # the subpath of the site
url: "https://eliottvincent.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: sofi.andrade10@gmail.com
      link: mailto:sofi.andrade10gmail.com
  follow:
    - name: Twitter
      link: http://twitter.com/SofiaAndrade__
      username: "@SofiaAndrade__"
    - name: LinkedIn
      link: http://linkedin.com/in/sofia-andrade1
